on:
  push:
    branches: [ main ]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"
      PYTHONIOENCODING: "utf-8"
      LANG: "C.UTF-8"
    permissions:
      contents: write
    steps:
      - uses: choam2426/AI-Algorithm-Mentor@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_PROVIDER: anthropic              # openai, google, anthropic
          MODEL_NAME: claude-sonnet-4-5  # 모델명 (선택사항)
          ANTHROPIC_API_KEY	: ${{ secrets.ANTHROPIC_API_KEY }}
          REVIEW_LANGUAGE: korean           # korean, english, etc..
